---
apiVersion: v1
kind: Service
metadata:
  name: front-end
  labels:
    name: front-end
  annotations:
    fabric8.io/expose: "true"
    fabric8.io/ingress.annotations: "kubernetes.io/ingress.class: nginx"
    fabric8.io/exposeUrl: http://socks.jx.bieri.online
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8079
    name: socks
  selector:
    name: front-end
